SocialEyes/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SocialEyes.Data;
using SocialEyes.Data.DBModels;
using Microsoft.AspNetCore.Http.Extensions;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace SocialEyes.Controllers
{
    public class ImageController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ImageController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Open(int id)
        {
            var imageModel = _context.Images.FirstOrDefault(m => m.Id == id);
            return View(imageModel);
        }

        public IActionResult Delete(int id)
        {
            var imageModel = _context.Images.FirstOrDefault(m => m.Id == id);


            if (imageModel == null)
            {
                return NotFound();
            }

            return View(imageModel);
        }

        // POST: Gallery/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var imageModel = await _context.Images.FindAsync(id);
            int GalleryId = imageModel.GalleryID;
            _context.Images.Remove(imageModel);
            await _context.SaveChangesAsync();
            //return RedirectToAction("OpenWithId/" + GalleryId,"Gallery");
            return RedirectToAction("Index", "Gallery");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateCommentAsync([Bind("CommentValue,ImageId")]CommentModel cm)
        {
            if (ModelState.IsValid)
            {
                cm.UserId= User.FindFirst(ClaimTypes.NameIdentifier).Value;
                cm.DateCreated = DateTime.Now;
                _context.Add(cm);
                await _context.SaveChangesAsync();
                
            }
            return RedirectToAction("Open/" + cm.ImageId);
        }
    }
}

SocialEyes/Views/Shared/_AddComment.cshtml
@model SocialEyes.Data.DBModels.CommentModel

<div class="panel-footer">
    <div class="input-group">
        <form id="formComment" method="post" asp-controller="Image" asp-action="CreateCommentAsync">
            <input asp-for="@Model.CommentValue" id="btn-input" required type="text" class="form-control input-sm chat_input" placeholder="Write your message here..." />
            <input hidden asp-for="@Model.ImageId" value="@Model.ImageId"/>            
                <input type="submit" class="btn btn-primary" id="btn-chat" value="Post"/>           
        </form>
    </div>
</div>
            

SocialEyes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SocialEyes</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script type="text/javascript" src="~/js/jquery.qrcode.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
        <script type="text/javascript" src="~/js/jquery.qrcode.js"></script>
        <script type="text/javascript" src="~/js/qrcode.js"></script>
        <script src="//platform-api.sharethis.com/js/sharethis.js#property=5c09595935e54100118bf3ad&product=inline-share-buttons"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script type="text/javascript" src="~/js/jquery.qrcode.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
        <script type="text/javascript" src="~/js/jquery.qrcode.js"></script>
        <script type="text/javascript" src="~/js/qrcode.js"></script>
        <script src="//platform-api.sharethis.com/js/sharethis.js#property=5c09595935e54100118bf3ad&product=inline-share-buttons"></script>
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SocialEyes</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <!--<li><a asp-area="" asp-controller="Gallery" asp-action="Index">Gallery</a></li>
                    <li><a asp-area="" asp-controller="Gallery" asp-action="Upload">Upload</a></li>-->
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - SocialEyes</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

SocialEyes/Views/Shared/_SocialSharing.cshtml
@* Find more SVG icons on https://simpleicons.org/ *@

@model SocialEyes.Data.DBModels.GalleryModel
@{
    string currentUrl = Context.Request.Scheme + "://" + Context.Request.Host;
    string enc = System.Net.WebUtility.UrlEncode(currentUrl + "/Gallery/Open/" + Model.UniqueUrl);
    string subject = "Invitation to view photo gallery:";
}

<aside class="socialsharing">
    <a href="https://twitter.com/intent/tweet?url=@enc&text=@subject" target="_blank" rel="noopener noreferrer nofollow">
        <svg role="img" aria-labelledby="_tw">
            <title id="_tw">Share on Twitter</title>
            <path d="M23.954 4.569c-.885.389-1.83.654-2.825.775 1.014-.611 1.794-1.574 2.163-2.723-.951.555-2.005.959-3.127 1.184-.896-.959-2.173-1.559-3.591-1.559-2.717 0-4.92 2.203-4.92 4.917 0 .39.045.765.127 1.124C7.691 8.094 4.066 6.13 1.64 3.161c-.427.722-.666 1.561-.666 2.475 0 1.71.87 3.213 2.188 4.096-.807-.026-1.566-.248-2.228-.616v.061c0 2.385 1.693 4.374 3.946 4.827-.413.111-.849.171-1.296.171-.314 0-.615-.03-.916-.086.631 1.953 2.445 3.377 4.604 3.417-1.68 1.319-3.809 2.105-6.102 2.105-.39 0-.779-.023-1.17-.067 2.189 1.394 4.768 2.209 7.557 2.209 9.054 0 13.999-7.496 13.999-13.986 0-.209 0-.42-.015-.63.961-.689 1.8-1.56 2.46-2.548l-.047-.02z"></path>
        </svg>
    </a>
    <a href="mailto:?subject=@subject&amp;body=@enc " target="_blank" rel="noopener noreferrer nofollow">
        <svg role="img" aria-labelledby="_em">
            <title id="_em">Email</title>
            <path d="M24 7.387v10.478c0 .23-.08.424-.238.576-.158.154-.352.23-.58.23h-8.547v-6.959l1.6 1.229c.102.085.229.126.379.126.148 0 .277-.041.389-.127L24 7.387zm-9.365-2.021h8.547c.211 0 .393.063.543.192.15.128.234.3.248.51l-7.369 5.876-1.969-1.549V5.366zM13.404.864v22.271L0 20.819V3.244L13.406.864h-.002zm-4.049 11.18c-.02-1.133-.313-2.072-.879-2.814-.555-.74-1.275-1.131-2.131-1.164-.824.033-1.529.423-2.1 1.164-.57.742-.855 1.682-.87 2.814.015 1.117.315 2.047.885 2.791.571.74 1.274 1.133 2.101 1.176.855-.035 1.574-.424 2.145-1.17.57-.748.87-1.68.885-2.797h-.036zm-3.12-2.482c.431.02.794.256 1.083.717.285.461.435 1.045.435 1.752 0 .721-.149 1.307-.435 1.771-.301.464-.66.704-1.096.704s-.795-.226-1.095-.69-.435-1.05-.435-1.754c0-.705.135-1.291.435-1.74.284-.45.646-.69 1.081-.721l.027-.039z"></path>
        </svg>
    </a>
</aside>